# "$make" compiles any missing or out_of_date objects , then relinks if needed.
# "$make clean" removes all files generated by the compiler (allows for clean compile)
# "$make turnin.txt" compiles (if needed), then runs the program and the checker.
# "$make clean_check" removes all files generated by running the above (outfiles, etc.)
# "$make valgrind" compiles (if needed), then runs the program through valgrind.
# Don't touch "$make depend"

CXX = g++
CXXFLAGS = -std=c++11 -g -Wall
SRCS = main.cpp AVL.cpp Node.cpp
OBJS = $(SRCS:.cpp=.o)
MAIN = Lab7_AVL

all: $(MAIN)

$(MAIN): $(OBJS)
	$(CXX) $(CXXFLAGS) -o $(MAIN) $(OBJS)

.cpp.o:
	$(CXX) $(CXXFLAGS) -c -o $@ $<

clean_build:
	$(RM) *.o $(MAIN)

valgrind: $(MAIN)
	valgrind ./$(MAIN)

turnin.txt: $(MAIN)
	./$(MAIN)
	bash check.sh

clean_check:
	$(RM) turnin.txt details.txt out_file*

clean: clean_check clean_build

depend: $(SRCS)
	makedepend -- $(CXXFLAGS) -- $^
	$(RM) Makefile.bak

# DO NOT DELETE

main.o: AVL.h AVLInterface.h NodeInterface.h Node.h
AVL.o: AVL.h AVLInterface.h NodeInterface.h Node.h
Node.o: Node.h NodeInterface.h
